# Generated by Django 5.0.3 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('wish', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
