# Generated by Django 5.0.3 on 2024-03-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_wish_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
