# Generated by Django 5.0.3 on 2024-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0003_wish_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('attendance', models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default='Có', max_length=10)),
                ('party', models.CharField(choices=[('Nhà Trai', 'Nhà Trai'), ('Nhà Gái', 'Nhà Gái')], default='Nhà Trai', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
