# Generated by Django 5.0.3 on 2024-03-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0004_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='email',
        ),
    ]
